#!/bin/sh

set -ex

cargo check --all-targets --all-features
cargo +nightly fmt -- --check
cargo clippy --offline --all-targets --all-features -- -D warnings
cargo test --offline --all-targets --all-features
cargo test --offline --all-features --doc
