#!/bin/bash
set -ex

function check () {
    cargo fmt -- --check
    cargo clippy --locked --all-targets -- -D warnings
    cargo test --locked --all-targets
}

check
pushd grammar && check && popd
pushd highlight && check && popd
