name: cffconvert

on:
  pull_request:
    paths:
      - CITATION.cff
  push:
    paths:
      - CITATION.cff

permissions:
  contents: read

jobs:
  validation:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: cffconvert
        uses: citation-file-format/cffconvert-github-action@4cf11baa70a673bfdf9dad0acc7ee33b3f4b6084
        with:
          args: "--validate"
