name: Publish

on:
  push:
    tags: v*

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install x11 deps
        run: sudo apt update && sudo apt install xorg-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout git submodules
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run checks
        run: ./scripts/check
      - name: Build
        run: ./scripts/build
      - name: Publish zee-grammar
        run: |
          cd grammar
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish
      - name: Publish zee-highlight
        run: |
          cd highlight
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish
      - name: Publish zee
        run: |
          cd core
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish
